version: "3.8"
services:
  react-app:
    build: .
    container_name: landing_zone
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./src:/app/src
    restart: always
